### ISSUE TITLE
Support for range

### ISSUE THREAD

**Issue by alexherbo2** [occivink/kakoune-number-comparison#4]
It could be nice to be able to select a number between a certain range, e.g. a number between 12 and 24, inclusive and exclusive.

**Comment by occivink** [comment]
I thought about this one, but I'm not sure for the following reasons

* what syntax do you use? `<= 12` is clear enough, but how do you specify a range?
* it can be easily expressed by doing two operations, first `>= 12` and then `< 24`

**Comment by alexherbo2** [comment]
It doesn’t look easy to do in two operations without a <kbd>z</kbd> dance.

``` kak
number-comparison ... 12 24
```

`..` for inclusive and `...` exclusive.

We could make the command accept a list of tuples, but _and_ doesn’t look easy to express with regexes.

``` kak
number-comparison >= 12 < 24
```

**Comment by occivink** [comment]
>It doesn’t look easy to do in two operations without a z dance.

It's not that bad, you can do
`number-comparison >= 12 ; exec '%s<ret>' ; number-comparison < 24 ; exec '<a-k><ret>'` 

But your syntax proposition is good. I'll consider it

**Comment by occivink** [comment]
I've decided that implementing this requires too much special casing for what seems like little benefits.
